#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/contract/node_modules/.pnpm/near-typescript-json-schema@0.55.0/node_modules/near-typescript-json-schema/bin/node_modules:/contract/node_modules/.pnpm/near-typescript-json-schema@0.55.0/node_modules/near-typescript-json-schema/node_modules:/contract/node_modules/.pnpm/near-typescript-json-schema@0.55.0/node_modules:/contract/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/contract/node_modules/.pnpm/near-typescript-json-schema@0.55.0/node_modules/near-typescript-json-schema/bin/node_modules:/contract/node_modules/.pnpm/near-typescript-json-schema@0.55.0/node_modules/near-typescript-json-schema/node_modules:/contract/node_modules/.pnpm/near-typescript-json-schema@0.55.0/node_modules:/contract/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../near-typescript-json-schema@0.55.0/node_modules/near-typescript-json-schema/bin/typescript-json-schema" "$@"
else
  exec node  "$basedir/../../../../../near-typescript-json-schema@0.55.0/node_modules/near-typescript-json-schema/bin/typescript-json-schema" "$@"
fi
